name: Build Python Interpreter for UEFI using VS2019

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019
    env:
      NASM_PREFIX: "C:\\Program Files\\NASM"
    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install NASM
      run: choco install nasm

    - name: VSWhere
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"

    - name: Setup environment for Visual Studio 2019 Build Tools
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build\vcvarsall.bat" x86
        set

    - name: Clone EDK2
      run: |
        git clone https://github.com/tianocore/edk2.git"
        cd edk2
        git submodule update --init

    - name: Copy edk2-libc contents to edk2
      run: |
        dir
        cmd /c xcopy /E /I /Y AppPkg edk2\AppPkg
        cmd /c xcopy /E /I /Y StdLib edk2\StdLib
        cmd /c xcopy /E /I /Y StdLibPrivateInternalFiles edk2\StdLibPrivateInternalFiles

    - name: Build EDK2 Base Tools
      run: |
        cd edk2
        dir
        edksetup.bat ForceRebuild

    - name: Build Python UEFI
      run: |
        cd edk2
        call edksetup.bat
        cd AppPkg\Applications\Python\Python-3.6.8\
        python srcprep.py
        cd ..\..\..\..\..\
        build -t VS2019 -a X64 -b RELEASE -p AppPkg\AppPkg.dsc

    - name: Create Python UEFI package
      run: |
        dir
        cd edk2\AppPkg\Applications\Python\Python-3.6.8\
        dir
        call create_python_pkg.bat VS2019 RELEASE X64 myUEFIPy

    - name: List build artifacts
      run: |
        dir /S edk2\myUEFIPy

    - name: Upload build output as artifact
      uses: actions/upload-artifact@v4
      with:
        name: myUEFIPy-build-VS2019-output
        path: edk2\myUEFIPy\**\*
